"""Add razorpay signature and webhook events table

Revision ID: 0e8f023fd586
Revises: 3facb90ba899
Create Date: 2026-08-22 15:50:27.765964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e8f023fd586'
down_revision = '3facb90ba899'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_webhook_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.String(length=100), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment_webhook_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_webhook_events_event_id'), ['event_id'], unique=True)

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('razorpay_signature', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_column('razorpay_signature')

    with op.batch_alter_table('payment_webhook_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_webhook_events_event_id'))

    op.drop_table('payment_webhook_events')
    # ### end Alembic commands ###
