"""Added notes and coupon_id to orders

Revision ID: 2181da5acb1e
Revises: 365e06485900
Create Date: 2026-08-25 16:03:38.983204

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2181da5acb1e'
down_revision = '365e06485900'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('site_banners')
    with op.batch_alter_table('admin_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_admin_users_code'))
        batch_op.drop_index(batch_op.f('idx_admin_users_email'))

    op.drop_table('admin_users')
    with op.batch_alter_table('otp_verifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_otp_verifications_email'))
        batch_op.drop_index(batch_op.f('idx_otp_verifications_expires'))

    op.drop_table('otp_verifications')
    op.drop_table('site_settings')
    op.drop_table('marquee_images')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_coupon_id'), ['coupon_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_coupon_id'))

    op.create_table('marquee_images',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('image_url', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('display_order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('marquee_images_pkey'))
    )
    op.create_table('site_settings',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('hero_title', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('hero_subtitle', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('hero_cta_text', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('announcement_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('announcement_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('contact_email', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('contact_phone', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('studio_address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('footer_brand_bio', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('copyright_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('site_settings_pkey'))
    )
    op.create_table('otp_verifications',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('otp_code', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('reset_token', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('is_used', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('otp_verifications_pkey'))
    )
    with op.batch_alter_table('otp_verifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_otp_verifications_expires'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_otp_verifications_email'), ['email'], unique=False)

    op.create_table('admin_users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('admin_code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=30), server_default=sa.text("'SuperAdmin'::character varying"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("role::text = ANY (ARRAY['SuperAdmin'::character varying, 'Manager'::character varying, 'Staff'::character varying]::text[])", name=op.f('admin_users_role_check')),
    sa.PrimaryKeyConstraint('id', name=op.f('admin_users_pkey')),
    sa.UniqueConstraint('admin_code', name=op.f('admin_users_admin_code_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('email', name=op.f('admin_users_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    with op.batch_alter_table('admin_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_admin_users_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('idx_admin_users_code'), ['admin_code'], unique=False)

    op.create_table('site_banners',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('subtitle', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('caption', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('image_url', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('cta_text', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('cta_link', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('display_order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('site_banners_pkey'))
    )
    # ### end Alembic commands ###
