"""Add shipping address snapshot to orders

Revision ID: 3facb90ba899
Revises: a91a3f924547
Create Date: 2026-08-22 15:38:44.565747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3facb90ba899'
down_revision = 'a91a3f924547'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shipping_full_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('shipping_phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('shipping_address_line1', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('shipping_address_line2', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('shipping_city', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('shipping_state', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('shipping_postal_code', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('shipping_country', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('shipping_country')
        batch_op.drop_column('shipping_postal_code')
        batch_op.drop_column('shipping_state')
        batch_op.drop_column('shipping_city')
        batch_op.drop_column('shipping_address_line2')
        batch_op.drop_column('shipping_address_line1')
        batch_op.drop_column('shipping_phone')
        batch_op.drop_column('shipping_full_name')

    # ### end Alembic commands ###
