"""Add supabase_uid to users

Revision ID: 50375f135063
Revises: 9befdefd266d
Create Date: 2026-08-22 15:01:40.902768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50375f135063'
down_revision = '9befdefd266d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('supabase_uid', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_supabase_uid'), ['supabase_uid'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_supabase_uid'))
        batch_op.drop_column('supabase_uid')

    # ### end Alembic commands ###
