"""Add shipment_tracking_events table

Revision ID: 7a8b9c0d1e2f
Revises: 8f9a2b3c4d5e
Create Date: 2026-08-22 23:25:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a8b9c0d1e2f'
down_revision = '8f9a2b3c4d5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'shipment_tracking_events',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('shipment_id', sa.Integer(), nullable=False),
        sa.Column('status', sa.String(length=50), nullable=False),
        sa.Column('external_status', sa.String(length=100), nullable=True),
        sa.Column('description', sa.String(length=255), nullable=True),
        sa.Column('location', sa.String(length=255), nullable=True),
        sa.Column('event_timestamp', sa.DateTime(timezone=True), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shipment_tracking_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shipment_tracking_events_event_timestamp'), ['event_timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_shipment_tracking_events_shipment_id'), ['shipment_id'], unique=False)


def downgrade():
    with op.batch_alter_table('shipment_tracking_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shipment_tracking_events_shipment_id'))
        batch_op.drop_index(batch_op.f('ix_shipment_tracking_events_event_timestamp'))

    op.drop_table('shipment_tracking_events')
