"""Add Shiprocket columns and shipment webhook event table

Revision ID: 8f9a2b3c4d5e
Revises: 0e8f023fd586
Create Date: 2026-08-22 20:44:30.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f9a2b3c4d5e'
down_revision = '0e8f023fd586'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'shipment_webhook_events',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('event_id', sa.String(length=100), nullable=False),
        sa.Column('event_type', sa.String(length=100), nullable=False),
        sa.Column('status', sa.String(length=30), nullable=False),
        sa.Column('processed_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shipment_webhook_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shipment_webhook_events_event_id'), ['event_id'], unique=True)

    with op.batch_alter_table('shipments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shiprocket_order_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('courier_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('pickup_scheduled_at', sa.DateTime(timezone=True), nullable=True))


def downgrade():
    with op.batch_alter_table('shipments', schema=None) as batch_op:
        batch_op.drop_column('pickup_scheduled_at')
        batch_op.drop_column('courier_id')
        batch_op.drop_column('shiprocket_order_id')

    with op.batch_alter_table('shipment_webhook_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shipment_webhook_events_event_id'))

    op.drop_table('shipment_webhook_events')
