"""Add is_trending to products

Revision ID: a91a3f924547
Revises: 50375f135063
Create Date: 2026-08-22 15:12:44.433973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a91a3f924547'
down_revision = '50375f135063'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_trending', sa.Boolean(), nullable=False))
        batch_op.create_index(batch_op.f('ix_products_is_trending'), ['is_trending'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_is_trending'))
        batch_op.drop_column('is_trending')

    # ### end Alembic commands ###
